### ISSUE TITLE
GKE no longer supports Basic Authentication with username/password

### ISSUE THREAD

**Issue by pstephenson02** [OctopusDeploy/TenPillarsK8s#4]
In the first chapter titled Repeatable Kubernetes Deployments, the book shows us how to create an Account in Octopus that corresponds to our GKE cluster credentials. Following along with this I just created a new cluster in GKE and discovered that basic auth has been deprecated and removed in the current version.

https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_static_password
> Note: Basic authentication is deprecated and has been removed in GKE 1.19 and later.

[Current version](https://cloud.google.com/kubernetes-engine/docs/release-notes) shows as GKE 1.19 😐 

This is probably a losing battle for keeping up with all the different Kubernetes cloud platforms, but maybe just a note in the book mentioning this would be helpful to readers?

**Comment by mcasperson** [comment]
We expect to have integrated Google auth for K8s clusters this cycle, so the book will likely be updated to use that as the admin login. The changes are hard to keep on top of, but at least if we use a support auth mechanism Octopus itself should provide a level of abstraction.

**Comment by mcasperson** [comment]
The book has been updated to show the new GKE auth options instead of username and password.
